### ISSUE TITLE
Fatal error: Uncaught Error: Class 'btcpaypaymentModuleFrontController' not found

### ISSUE THREAD

**Issue by matahr** [btcpayserver/prestashop-plugin#1]
PrestaShop 1.7.7.0

Fatal error: Uncaught Error: Class 'btcpaypaymentModuleFrontController' not found in /var/www/prestashop/classes/controller/Controller.php:233 Stack trace: #0 
/var/www/prestashop/classes/Dispatcher.php(510): ControllerCore::getController('btcpaypaymentMo...') #1 /var/www/prestashop/index.php(28): DispatcherCore->dispatch() #2  
{main} thrown in /var/www/prestashop/classes/controller/Controller.php on line 233

**Comment by BitcoinMitchell** [comment]
This bug reports doesn't give me a lot of information. Did you install it fresh or did you upgrade from an earlier version?

**Comment by BitcoinMitchell** [comment]
@matahr For some reason the release of this plugin contains incorrect code. Could you try this one for me?

[btcpay.zip](https://github.com/btcpayserver/prestashop-plugin/files/5920228/btcpay.zip)

**Comment by BitcoinMitchell** [comment]
This issue has been resolved via #2 and I can confirm that the ZIP-file attached to `Release v0.1.2` contains the proper files. I've also gone back and updated all the old versions.

Please try again and report back @matahr :)
