### ISSUE TITLE
[Bug]: undefined method named getConfiguration()

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/prestashop-plugin#139]
### What is your BTCPay Server version?

unknown

### How did you deploy BTCPay Server?

unknown

### What is version of the PrestaShop plugin are you using?

BTCPay plugin v6.1.4
PrestaShop v8.0.4

### What happened?

A user reported that there is an error of "undefined method named 'getConfiguration()' of class `BTCPay\Controller\Admin\Improve\Payment\ConfigureController` when clicking on "configure" after installing the plugin.

### How did you encounter this bug?

1. Install the plugin
2. click "configure"
3. error

![image](https://github.com/btcpayserver/prestashop-plugin/assets/1136761/2693dbbd-dd9e-49ef-bed3-fa4c16ae1428)

### Relevant log output

```shell
see above
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ndeet** [comment]
I think the problem is because 8.0.x did not have that function and it was introduced in 8.1.0, see https://github.com/PrestaShop/PrestaShop/blob/8.0.x/src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php

@BitcoinMitchell can you do a version constraint for the plugin so it does not install with 8.0.x or do a workaround via a version check by calling FrameworkBundleAdminController::configuration in case of 8.0.4 and getConfiguration() on newer versions?

**Comment by ndeet** [comment]
Breaking change happened in #93 here https://github.com/btcpayserver/prestashop-plugin/pull/93/files#diff-3650da1e943f4fb384f11035f6e3d319f60175f7fb19512e47aeebf92ad71e5a

**Comment by BitcoinMitchell** [comment]
There is a framework restraint as defined in https://github.com/btcpayserver/prestashop-plugin/blob/6.x/modules/btcpay/src/Constants.php#L15

Didn't notice that this was a new 8.1.0 change, will release a fix when I have time later today.
