### ISSUE TITLE
[Bug]: Cannot configure BTCPay

### ISSUE THREAD

**Issue by Nisaba** [btcpayserver/prestashop-plugin#158]
### What is your BTCPay Server version?

I'm running Prestahop 8.2.0

### How did you deploy BTCPay Server?

Prestashop is installed in a share hosting

### What is version of the PrestaShop plugin are you using?

Prestashop plugin 6.2.1

### What happened?

I've just installed the plugin in Prestashop.
When I clicked in the configure button, I was redirected to the dashboard.

### How did you encounter this bug?

Now, when I click on Payment / BTCPay Server (left menu), I'm also redirected to the dashboard

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by BitcoinMitchell** [comment]
I've just setup a clean PrestaShop instance using [PrestaShop Kickstarter](https://github.com/PrestaShopCorp/docker-compose-kickstarter) and installed v6.2.1. It redirected me straight to the configure page and both the sidebar link and the module list button work. 

![image](https://github.com/user-attachments/assets/55190270-feca-41f7-bb3b-a32fb0dd351d)

---

As of right now, that means I cannot re-produce your issues. Could you provide with additional logs/details?

**Comment by Nisaba** [comment]
Well... it works after restarting the VPS..
sorry for the inconvenience

**Comment by BitcoinMitchell** [comment]
> Well... it works after restarting the VPS.. sorry for the inconvenience

Weird that it happened, but if it works now, I'm happy. Closing the issue.
