### ISSUE TITLE
[Bug]: Error after submitting API Key

### ISSUE THREAD

**Issue by deverickapollo** [btcpayserver/prestashop-plugin#169]
### What is your BTCPay Server version?

I'm running BTCPay Server v2.0.3 and Prestashop v8.0

### How did you deploy BTCPay Server?

BTCPay Server is deployed via umbrel 

### What is version of the PrestaShop plugin are you using?

I'm running v6.2.1 of the Prestashop plugin

### What happened?

After submitting the API key, I receive a 500 error. Enabling debug on prestashop returns the error:

An exception has been thrown during the rendering of a template ("Error during GET to https://btcpay.server.com/api/v1/stores/storeID/payment-methods/LightningNetwork. Got response (410): {"code":"unsupported-in-v2","message":"This route isn't supported by BTCPay Server 2.0 and newer. Please update your integration."}").

### How did you encounter this bug?

I submitted the API key and clicked the save button and received a 500 error.

### Relevant log output

```shell
Debugger is returning the error from L198 of `modules/btcpay/views/templates/admin/configure.html.twig` :

` {% for paymentMethod in client.offChain().getPaymentMethods(storeId) %}`
```

### What browser do you use (if useful)?

Tested with Chrome

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by BitcoinMitchell** [comment]
@ndeet I thought we upgraded `btcpayserver/btcpayserver-greenfield-php` to support BTCPayServer 2.0?

**Comment by BitcoinMitchell** [comment]
Looking at `btcpayserver/btcpayserver-greenfield-php` it doesn't specify that `StorePaymentMethodLightningNetwork` and `StorePaymentMethodOnChain` are deprecated (only mentioned deprecations are here: https://github.com/btcpayserver/btcpayserver-greenfield-php/issues/51).

**Comment by BitcoinMitchell** [comment]
I've uploaded a potential fix in https://github.com/btcpayserver/prestashop-plugin/pull/170, could you test that @deverickapollo? Thank you in advance :)

**Comment by deverickapollo** [comment]
The endpoint appears to be documented as planned for deprecation [here under removed routes](https://github.com/btcpayserver/btcpayserver/issues/5964#issue-2272785957).

@BitcoinMitchell - I've tested #170 and can confirm I was able to connect to BTCPay. From the Prestashop store, I am able to see the linked store and related server information. 
![Screenshot 2024-11-24 at 10 52 03 AM](https://github.com/user-attachments/assets/f69c6353-d601-4ecb-a17b-fb898bf28008)

During invoice creation, the UI is reporting a server error. 
![Screenshot 2024-11-24 at 11 14 02 AM](https://github.com/user-attachments/assets/5fcc1164-88e7-4a0c-9272-8545003a9bd0)


Looking at btcpayserver, on invoice creation I see the following error: 

```
Microsoft.AspNetCore.Server.Kestrel: Connection id "0XXXXXXXX, Request id "0XXXXXXXX1AL:00000009": An unhandled exception was thrown by the application.
System.InvalidOperationException: The exception handler configured on ExceptionHandlerOptions produced a 404 status response. This InvalidOperationException containing the original exception was thrown since this is often due to a misconfigured ExceptionHandlingPath. If the exception handler is expected to return 404 status responses then set AllowStatusCode404Response to true.
 ---> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "PK_AddressInvoices"

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader, Boolean async, CancellationToken cancellationToken)
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "PK_AddressInvoices"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: public
    TableName: AddressInvoices
    ConstraintName: PK_AddressInvoices
    File: nbtinsert.c
    Line: 649
    Routine: _bt_check_unique
```

**Comment by ndeet** [comment]
@deverickapollo about the error on invoice creation, does this also happen when you create an invoice directly on your BTCPay Server store? It looks like an internal error that's not caused by the api call, I think. 

Did you do a fresh 2.0.3 install or upgrade from 1.13.x?

**Comment by ndeet** [comment]
> @ndeet I thought we upgraded `btcpayserver/btcpayserver-greenfield-php` to support BTCPayServer 2.0?

Yes we did but I was not aware that you used the specific on-chain and LN endpoints as we already as the get all payment methods already had covered both cases in the library (which the official API did not to that extend). But you are right we should mark those as deprecated with 2.0, I hoped to keep the library without any breaking change but it seems this is one such case. Maybe it would work to mimic the old behaviour too, will think about it a bit. 

Thanks for the quick fix :hugs:

**Comment by deverickapollo** [comment]
@ndeet - I did see the same error attempting to manually create an invoice directly on the btcpay server. I toggled the Supported Transaction Currencies and now I am able to create invoices again. I'm not sure if it was that or something else but it works now. I confirmed btcpay is also creating invoices for Prestashop now. Thanks for jumping on this!

**Comment by BitcoinMitchell** [comment]
I'll look into `Supported Transaction Currencies` and add a comment to the `README.md`/docs on BTCPayServer. 

Thank you for your extensive bug report and help!
