### ISSUE TITLE
Error 504 

### ISSUE THREAD

**Issue by Grafimia** [btcpayserver/prestashop-plugin#17]
BTCPay PrestaShop plugin is a bridge between your server (payment processor) and your e-commerce store. No matter if you're using a self-hosted or third-party solution from step 2, the pairing process is identical.

1. In the BTCPay server url-field, enter the full URL of your host (including the https) – https://btcpay.mydomain.com
2. Select the default transaction speed (this will change how much BTCPay recommends as transaction fee)
3. Select the relevant order mode for your store (order is created before or after payment)
4. Go to your BTCPay server, select a store, open its settings and select "Access Tokens".
5. Click on "Create a new token", select your store and then approve. 5.1. You will see: "Server initiated pairing code: XXXX".
6. Enter your pairing code.
7. Press save. Prestashop will now attempt to make a connection with your BTCPayServer.
8. A message will be shown if the connection was successful.
9. It's recommended to do a test purchase.

Point 4 to 6 I don't know how to do. In the module version 1.0.1 (5.0) not to be the same use.
Can I do the point 4 and 5 but the 6 I don't know where I have to put the pairing code?

I do the installation but when my PrestaShop try to connect doesn't work revert a 504 error.

**Comment by BitcoinMitchell** [comment]
Ah, the pairing code is used by the v4 version of this plugin (branch [4.x](https://github.com/btcpayserver/prestashop-plugin/tree/4.x), last release [v4.0.3](https://github.com/btcpayserver/prestashop-plugin/releases/tag/v4.0.3)), which was superseded today by v5. I still need to update the documentation on the website. My apologies. 

---

If you are using v5.0.1 (module version 5.0.1), you need to connect to your BTCPay Server by filling in the proper host (for example, `https://testnet.demo.btcpayserver.org`) and pressing `Connect`. Once you've done that  you'll be redirected to your BTCPay Server instance and asked to create an API key (make sure to select a single store for all permissions). Once done, you'll be redirected back to Prestashop and it will create a webhook for you. 

If you get a 504 error, it means that the server gateway has timed out. Make sure that the reverse proxy you are using is running (if you use something like [btcpayserver-docker](https://github.com/btcpayserver/btcpayserver-docker) with Nginx as the reverse proxy).

If you need further help, feel free to contact me on [Mattermost](https://chat.btcpayserver.org/btcpayserver/channels/integrations-development).

**Comment by Grafimia** [comment]
OK, thanks, I will try again. See you on Mattermost.

I dont Know how its works (make sure to select a single store for all permissions) i only see a select field but dosent select nothing only have ading another shop. ¿¿??

**Comment by BitcoinMitchell** [comment]
~~I've [created a pull request](https://github.com/btcpayserver/btcpayserver-doc/pull/987) to update the documentation.~~ [The documentation has been updated.](https://docs.btcpayserver.org/PrestaShop/)
