### ISSUE TITLE
Legacy controller admin_btcpay_configure on prestashop 1.7.4 does not work

### ISSUE THREAD

**Issue by woodyst** [btcpayserver/prestashop-plugin#20]
**Describe the bug**
Module does not invoke legacy controller admin_btcpay_cofigure because (I think) redirectAdmin calling symphony controllers does not work in prestashop 1.7.4. When you open configuration of the module, you get page not found.

The problem is in my opinion in controllers/admin/AdminConfigureBTCPayController.php (legacy controller), in:

Steps to reproduce the behavior:Tools::redirectAdmin($this->context->link->getAdminLink('BTCPay', true, array(
        'route' => 'admin_btcpay_configure'
)));

I think there are two possible problems in this code:

- I think modules do not route to symphony controllers in this version, because in prestashop guide developers say symphony controllers is implemented in modules from prestashop version 1.7.5.
- Tools::redirectAdmin has different parameters in every version of prestashop, and I think the invocation in the module is from 1.7.5 or 1.7.7.

I do not know if there is another way to invoque redirectAdmin compatible with 1.7.4 and the module. I have been months trying to fix this module for my installation, because I can not upgrade PHP and prestashop in this machine (we have a lot of modifications and overloads and for upgrading our system we would have to rewrite a lot of code).

**To Reproduce**
1. Upload module on prestashop 1.7.4 control panel.
2. Click on 'Configure module'
3. See 'page not found' error.

**Expected behavior**
The module configuration form to be loaded.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version 1.3.6.0. 
- Deployment Method: Manual
 - Browser firefox, brave, chrome, falkon, ...

**Additional context**
I had to adapt module for php 7.0 for my installation, erasing php function return types in declarations, but this do not afect this issue, because code loads and problem is whith prestashop routes.

Thanks in advance.

Edu.

**Comment by BitcoinMitchell** [comment]
From what I understand, this is a feature request to support older versions of Prestashop. As stated in the readme, PrestaShop 1.7.7.0 or higher is required for both version 4.x and 5.x of this module. I chose this version as it's the one that is currently maintained and I am familiar with. I, sadly, do not have time to support other versions and I did not intend to do so when I rewrote it.

That said, [prestashop-plugin-legacy](https://github.com/btcpayserver/prestashop-plugin-legacy) should still work for you and thus I recommend you to use that.
