### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by eddgeo** [btcpayserver/prestashop-plugin#56]
Hi i have a problem with Plugin Prestashop:
    ```
This value should not be empty.
This value should not be empty.
This plugin expects all passed permissions to be given. Remove the new API key and try again.

```
Plugin [Release v5.1.5](https://github.com/btcpayserver/prestashop-plugin/releases/tag/v5.1.5)
Prestashop Version 1.7.8.6

**Comment by BitcoinMitchell** [comment]
This sounds like you got a PrestaShop security popup when coming back from BTCPay Server (see the example below). I am going to assume you pressed `I understand the risk`, which works, but all the $POST-data is removed when that happens, so you get an exception like that (which I should make more clear).

There is nothing I can do to stop PrestaShop for displaying this message and I'm not 100% sure when they happen. Please make sure your instances are deployed with HTTPS and publicly accessible, that seems to solve the issue for most people.

---

![image](https://user-images.githubusercontent.com/27309467/173251474-0c8f9e55-83f7-4f2a-a04d-bc199015ce80.png)


---

**Comment by BitcoinMitchell** [comment]
Starting with [v5.2.0](https://github.com/btcpayserver/prestashop-plugin/releases/tag/v5.2.0 ) you can also manually enter the API key. I still have been unable to resolve the `invalid token`-issue, as I'll have to contact PrestaShop itself and get some internal code fixed.

Please try out [v5.2.0](https://github.com/btcpayserver/prestashop-plugin/releases/tag/v5.2.0) if you are still interested in the plugin and if you are still having issues, feel free to re-open this issue.
