### ISSUE TITLE
Feature Request: Prestashop 8 support

### ISSUE THREAD

**Issue by BitcoinMitchell** [btcpayserver/prestashop-plugin#70]
We need to make sure that our module will work with the newly release Prestashop 8. Changes can be found here: https://devdocs.prestashop-project.org/8/modules/core-updates/8.0/

**Comment by powerpowera** [comment]
Looking forward for this. There's no other Bitcoin module for Prestashop 8.0.0+ right now.

**Comment by BitcoinMitchell** [comment]
Good to know that it is needed @powerpowera. I'll allocate some time tonight to actually check it out!

**Comment by BitcoinMitchell** [comment]
@powerpowera There is a test version available in https://github.com/btcpayserver/prestashop-plugin/pull/74. If you could help me out by testing it, that would be great!

**Comment by BitcoinMitchell** [comment]
Resolved via https://github.com/btcpayserver/prestashop-plugin/pull/84
