### ISSUE TITLE
503 errors in Prestashop when btcpayserver calls the notification URL

### ISSUE THREAD

**Issue by TacoScheltema** [btcpayserver/prestashop-plugin#8]
Hi, 
This is something to add to the documentation perhaps. I was struggling with this issue and I'm sure other prestashop users will run into the same issue:

When testing the prestashop-plugin I noticed 503 errors in the apache access logs:
```
xxx.xxx.xxx.xxx - - [29/Jan/2019:14:10:06 +0200] "POST /index.php?key=36018f52bc6635bc42fed58d52392449&fc=module&module=btcpay&controller=notification&id_lang=1 HTTP/1.1" 503 4717 "-" "-"
```
where xxx.xxx.xxx.xxx is the ip address of the btcpayserver that I was testing with.

I saw nothing in the apache error logs so it really had me wonder what was causing this issue.
Then it occurred to me that I had prestashop in maintenance mode with my home IP whitelisted. When I tried to connect to the shop from another IP address I received a 503 error.

Once I added the ip address of the btcpayserver to the list of maintenance IPs everything was working fine.

**Comment by olinkl** [comment]
Yeah, it's related to system administration but we sould give a word about it in doc.
Thanks
